### ISSUE TITLE
How to control the number of runs k-prototypes takes?

### ISSUE THREAD

**Issue by durgaswaroop** [nicodv/kmodes#127]
There is the parameter to control the max iterations but there doesn't seem to be any way t control the number of runs it takes. Is that how it is supposed to be? 
I'm running k-protoypes with 2 clusters on a dataset of 170000 records with a mix of categorical and numerical columns.
It has been almost an hour since it started and it is in Run #5 now. So, Want to know if there is a way I can use to reduce the number of runs it does.

**Comment by nicodv** [comment]
I believe you're looking for the `n_init` argument: https://github.com/nicodv/kmodes/blob/master/kmodes/kprototypes.py#L351

**Comment by durgaswaroop** [comment]
No, that's not what I'm looking for. I've set the `n_init` to 1 and it still went to Run number #5.

**Comment by nicodv** [comment]
Please show us what you've tried, in detail. There's not enough info here.

**Comment by nicodv** [comment]
You may have been stuck in the initialization loop, @durgaswaroop . Those retry numbers are hardcoded: https://github.com/nicodv/kmodes/blob/master/kmodes/kprototypes.py#L20

There's a good reason they're hardcoded, though, as the problem is likely with your data set/settings. I suggest you read the FAQ entry about initialization errors (at the bottom): https://github.com/nicodv/kmodes#faq
