### ISSUE TITLE
Add L1 as a dissimilarity function option for continuous variables

### ISSUE THREAD

**Issue by imamilion** [nicodv/kmodes#169]
A k-prototypes model fit can't be pickle-saved when a user-defined dissimilarity metric is used (see my [post](https://stackoverflow.com/questions/71249932/why-cant-my-k-prototypes-clustering-model-be-pickle-saved-when-based-on-a-user) on Stack Overflow). 

It seems to me that the issue would be solved if that user-defined dissimilary metric is actually implemented in the module, next to jaccard_dissim, euclidean_dissim, etc. Thus, it would be great to have some more commonly used distance functions implemented in the package. In my personal case, I'd like to be able to use L1 (Manhattan distance).

**Comment by nicodv** [comment]
There is such a large variety of potential distance functions to use for numerical clustering that I prefer to leave it to the users to provide them. `kmodes` specializes more in categorical distance functions.

But of course, feel free to submit a PR to add the function. :)

As for the pickling error, I'm not able to reproduce it. I suspect the problem lies with where you define your function. Have a look at this: https://www.pythonanywhere.com/forums/topic/27818/

A step-by-step reproducible example would help here.
