### ISSUE TITLE
What are the minimum characteristics that a binary matrix must meet to avoid the following error: "Insufficient Number of data since union is 0"?

### ISSUE THREAD

**Issue by Galy88** [nicodv/kmodes#178]
## Expected Behavior
Given a binary matrix, for example, of a 3x4 size, the KModes algorithm is expected to run and find to which cluster each row of the matrix should belong.

## Actual Behavior
Currently we have a 3x4 binary matrix, when we run the KModes algorithm, we immediately get the following message: "Insufficient Number of data since union is 0". With 3x4 binary matrixes sometimes the algorithm works. 

## Steps to Reproduce the Problem

1. Import libraries:
```
import numpy as np
from kmodes.kmodes import KModes
from kmodes.util.dissim import jaccard_dissim_binary
```

 2. Create binary matrix:
```
m = np.array([[0, 1, 1, 1],
              [0, 1, 1, 0],
              [1, 1, 1, 0]])
```

3. Adjust kmodes
` km = KModes(n_clusters=2, init='cao', random_state=0, n_jobs=-1, cat_dissim=jaccard_dissim_binary)`
4. Fit predict
`clusters = km.fit_predict(m)`

with this matrix the algorithm works: 
```
m2 = np.array([[1, 0, 0, 1], 
               [0, 1, 1, 0],
               [0, 1, 1, 0]])

clusters = km.fit_predict(m2)
```

## Specifications
  - kmodes 0.12.1
  - Python 3.7.13

**Comment by nicodv** [comment]
This appears to occur due to the `jaccard_dissim_binary` dissimilarity function, in combination with some specifics of the data set. Specifically, it appears this distance metric does not support situations where you have binary data, and all rows have the same value for a column.

You'll either need to:
- Add some more variety to your data.
- Use a different dissimilarity metric.
- Drop constant columns from the data beforehand. Since there's no point in differentiating between such columns, you may as well. That way, you can still use this distance function.
