### ISSUE TITLE
Very Slow with greater than 10k obs

### ISSUE THREAD

**Issue by ashish1610dhiman** [nicodv/kmodes#45]
It does not go ahead of this...

Init: initializing centroids
Init: initializing clusters
Starting iterations...

Even in gcs instance

**Comment by nicodv** [comment]
This is not due to the no. of observations, but likely due to your specific data. Note that Cao's init method can be very slow when n_clusters is large, maybe that's it.

You can run the benchmark.py script in the examples directory (which has 10k observations) to see if that works for you.

**Comment by paulaceccon** [comment]
Same here. I was able to run DBSCAN, but I'm struggling to run k-Prototype. Not sure about what strategy to follow to be able to run it.

**Comment by nicodv** [comment]
@paulaceccon , what are the dimensions of your problem? Also, please provide sample output, running in verbose mode.

**Comment by mpikoula** [comment]
Any insight as to why kprototypes is a lot slower than kmodes for similar datasets? Just trying to understand the algorithm better.

I've got only 3 numerical variables in my dataset(out of 12 total) and if I get rid of one and turn the other two into categories, kmodes runs instantaneously for n=1-10

**Comment by nicodv** [comment]
I've had some time to analyze this problem by profiling my code.

In order to determine the clusters in the k-means part of the algorithm, we need to divide the sums of attribute values by the number of points in the cluster. I realized I was caching the sums of the attributes alright, _but not the sums of the memberships in the clusters_.

The following commit resolves this:
https://github.com/nicodv/kmodes/commit/1a6a7be8e84ebaa4adf3e3e0de7ff5ddfbcb0453

I'm seeing very significant speedups as a result. :)

Thanks to everyone for pointing it out.

**Comment by nicodv** [comment]
Oh, and I've included a benchmark script specifically for k-prototypes in the examples folder.
