### ISSUE TITLE
Don't freeze version of packages

### ISSUE THREAD

**Issue by alxkolm** [nicodv/kmodes#49]
Please, don't freeze versions of packages
```
'numpy==1.12.1',
'scikit-learn==0.18.1',
'scipy==0.19.0'
```

**Comment by nicodv** [comment]
After reading https://blog.miguelgrinberg.com/post/the-package-dependency-blues, I've moved to ranges of dependency package versions:

```
install_requires=[
        'numpy>=1.13.0, <0.14.0',
        'scikit-learn>=0.18.0, <0.19.0',
        'scipy>=0.19.0, <0.20.0',
    ]
```

**Comment by shapiromatron** [comment]
scikit-learn has a few more recent [versions](https://github.com/scikit-learn/scikit-learn/releases), could this range be increased?

**Comment by nicodv** [comment]
@shapiromatron Unfortunately, scikit-learn 0.20 introduces some breaking changes to k-modes. I'm holding off for a bit, but feel free to try it and file a PR. :)

**Comment by shapiromatron** [comment]
Thanks @nicodv; I just wanted to make sure it really was required. I'll take a look at see what I can do....

**Comment by nicodv** [comment]
I seem to recall the sklearn compatibility tests have to be rewritten, @trevorstephens : https://github.com/nicodv/kmodes/blob/master/kmodes/tests/test_common.py

I've always had to customize that file entirely, because `kprototypes` takes an extra argument (`categoricals`) to the fit/predict methods and that breaks sklearn compatibility. I'd still like to comply as much as I can, though.

**Comment by trevorstephens** [comment]
Ah yes that makes sense. I saw something vaguely similar from Py-earth in the mailing list saying some of his tests failed due to extra args as well:

> I'm working on updating py-earth for some recent changes in scikit-learn and cython.  It seems like check_estimator has been significantly improved, and I'm working through making py-earth compliant with it.  I've hit the following issue, though.  It seems check_estimator tests score_samples using only X as an argument, and py-earth's score_samples requires y as well.  So, my question is: must score_samples work with just X (and therefore maybe I should just remove it from py-earth) or is it okay to have a score_samples that requires y, and I should try to find a workaround for check_estimator?

You might want to pile onto this PR with some suggestions for your package as was suggested for py-earth: https://github.com/scikit-learn/scikit-learn/pull/8022

**Comment by klepikhina** [comment]
I notice that when trying to run:
`km = KPrototypes(n_clusters=20, init='Huang', n_init=1, n_jobs=-1, verbose=1)`
that I get an error that says:
`__init__() got an unexpected keyword argument 'n_jobs'`
which might be an sklearn issue?
