### ISSUE TITLE
KPrototype fails on iris dataset

### ISSUE THREAD

**Issue by rbagd** [nicodv/kmodes#66]
I am having trouble running `kprototypes` algorithm on the standard `iris` dataset with some settings, although examples from the library itself seemed to work fine.

```
import pandas as pd
import numpy as np
from sklearn import datasets
from kmodes.kprototypes import KPrototypes

iris = datasets.load_iris()

data = pd.DataFrame(data = np.c_[iris['data'], iris['target']],
                    columns = iris['feature_names'] + ['target'])

kp = KPrototypes(n_clusters = 3, init = 'Huang', n_init = 1, verbose = True)
kp.fit_predict(data.values, categorical = [4])
```

Note that if `k = 2`, then this would run successfully. Here's the traceback of the above code.

```
Traceback (most recent call last):
  File "script.py", line 13, in <module>
    kp.fit_predict(data.values, categorical = [4])
  File "../python3.6/site-packages/kmodes/kmodes.py", line 376, in fit_predict
    return self.fit(X, **kwargs).predict(X, **kwargs)
  File "../python3.6/site-packages/kmodes/kprototypes.py", line 419, in fit
    self.verbose)
  File "../python3.6/site-packages/kmodes/kprototypes.py", line 196, in k_prototypes
    centroids = kmodes.init_huang(Xcat, n_clusters, cat_dissim)
  File "../python3.6/site-packages/kmodes/kmodes.py", line 43, in init_huang
    while np.all(X[ndx[0]] == centroids, axis=1).any():
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by nicodv** [comment]
Thanks, I was never able to reproduce this reported bug, but now I found it.

This bug occurred in the Huang initialization method. If a initialized centroid results in an empty cluster, we want to set the centroid to the closest point instead. This new centroid would ideally be unique, but the code didn't count on that not always being possible. I made it more robust now.

Fixed in: https://github.com/nicodv/kmodes/commit/02566e8d7f883f06221b60df9b87f971db6d9ca7

I also added the iris data set as an example, following your code.
